### PR TITLE
[mlflow] Avoid hardcoding `--default-artifact-root`

### PR DESCRIPTION
**Pull request by xadrianzetx**
#### What this PR does / why we need it:

As described in [cli help](https://github.com/mlflow/mlflow/blob/d112aedbc3faa21a688ce1a3545a75008ff2c6bd/mlflow/cli.py#L368-L379), default value is dependent on other flags passed to server, so we should leave it to the server to work out correct combination. Note that when using default `values.yaml`, behavior does not change between master and this PR.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [x] [DCO](https://github.com/community-charts/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Chart `artifacthub.io/changes` field updated (if exists)
- [x] Title of the PR starts with chart name (e.g. `[mlflow]`)
- [x] Unit tests written
- [x] `values.yaml` file fields documented
- [x] `README.md` file updated

### CODE REVIEW

**Comment by burakince** [comment]
Well, I think we need to recreate the snapshot files. You can delete the [__snapshot__](https://github.com/community-charts/helm-charts/tree/main/charts/mlflow/unittests/__snapshot__) folder and run the following command to recreate them.

```bash
helm unittest --helm3 --strict --file unittests/*.yaml --file unittests/**/*.yaml charts/mlflow
```

**Comment by burakince** [comment]
This is the error from default behaviour

```
│                                                                                             Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                             │
│ Option 'default-artifact-root' is required when backend store is not local file based.                                                                                                                                                                   │
│ Usage: mlflow server [OPTIONS]                                                                                                                                                                                                                           │
│ Try 'mlflow server --help' for help.                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                                          │
│ Error: Option 'default-artifact-root' is required when backend store is not local file based.
```

**Comment by burakince** [comment]
@xadrianzetx I remembered now. It gets an error without set `default-artifact-root` option.

**Comment by burakince** [comment]
Could you please describe to me your error case? Maybe I can find another way for it.

**Comment by xadrianzetx** [comment]
I'm essentially trying to follow deployment [scenario 5](https://www.mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access), but with `default-artifact-root` specified, it seems like [scenario 4](https://www.mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores) is actually used, which requires clients to handle auth to remote buckets themselves (Which I'd like to avoid).

**Comment by xadrianzetx** [comment]
Looking at [artifact root resolve code](https://github.com/mlflow/mlflow/blob/9cf4e2da819e704401e883b07a2efb0c2d000fff/mlflow/utils/server_cli_utils.py#L15-L35), it seems like option for remote backend store and local artifact store is illegal in mlflow server (`resolve_to_local` is `False`), and current chart overrides that when defaulting to `./mlruns`.

**Review by burakince — APPROVED** [review]

**Comment by burakince** [comment]
Hi @xadrianzetx 

I added `artifactRoot.proxiedArtifactStorage` flag to support [Scenario 5](https://www.mlflow.org/docs/latest/tracking.html#id32). Could you please review the changes?

**Review by xadrianzetx — COMMENTED** [review]
Looks great, thanks for helping me out!

**Comment by burakince** [comment]
Thank you so much for your contribution. Also, I added an example usage to [here](https://github.com/community-charts/examples/tree/main/mlflow-examples/proxied-artifact-storage-access-example).

**Pull request merged**
