### PR TITLE
[mlflow] Added db checker init container

### PR DESCRIPTION
**Pull request by ryshoooo**
#### What this PR does / why we need it:
Added an optional init container to both the deployment and migration job, which checks for the database availability. This is to make sure the database is available before starting the mlflow or the migrations container.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes no issue

#### Checklist

- [x] [DCO](https://github.com/community-charts/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] Chart `artifacthub.io/changes` field updated (if exists)
- [x] Title of the PR starts with chart name (e.g. `[mlflow]`)
- [x] Unit tests written
- [x] `values.yaml` file fields documented
- [x] `README.md` file updated

### CODE REVIEW

**Comment by burakince** [comment]
Hi @ryshoooo 

Sorry, I was busy the last few days. Currently, mlflow already uses [sqlalchemy](https://pypi.org/project/SQLAlchemy/) package and it's doing a database check before the connection. Could you please explain to me why do we need to have this init container?

**Comment by ryshoooo** [comment]
> Hi @ryshoooo
> 
> Sorry, I was busy the last few days. Currently, mlflow already uses [sqlalchemy](https://pypi.org/project/SQLAlchemy/) package and it's doing a database check before the connection. Could you please explain to me why do we need to have this init container?

Hi @burakince 

No worries :) Sure, the main reason is not to have the mlflow pod in a running/ready/serving state if the database is not available (i.e. when it's not actually ready/serving) and only start it up when we're sure the database is there and serving. This way I'll know that when the mlflow service is reachable, it's actually ready, which is useful especially since I have other services calling the mlflow API upon startup :)

But also it's not needed per se, it's an optional choice and useful for my case :) The current behavior is preserved as the default configuration.

**Comment by burakince** [comment]
Infinitive loops are dangerous. Let me add some circuit breakers to the script.

**Review by burakince — APPROVED** [review]

**Comment by burakince** [comment]
Hi @ryshoooo 

- When we use the exit from the script with an error code (e.g. `exit 1`), Kubernetes restarts the init container immediately. So I just added incremental wait time (by fibonacci number) for circuit breaker functionality.
- I moved the script to an external additional file. Because we use it in two different spaces and it will be always consistent now. Also, your editor can visualize it better now.
- I added some more logs and added labels to them. The monitoring system should understand and visualize them better now.
- I moved the flag to the upper level. Because I want to support MySQL ASAP and we can use the same script for it.

Please feel free to share your feedback.

Best,
Burak

**Review by burakince — APPROVED** [review]

**Comment by ryshoooo** [comment]
Hi @burakince 

Thanks a lot :) all looks good to me!

**Pull request merged**
